// Generated by https://quicktype.io

export interface AccountDetailsResponse {
  response: ResponseDetails;
  data?:     DataDetails[];
}

export interface DataDetails {
  id:        number;
  name:      string;
  last_name: string;
  sex:       string;
  age:       string;
  grade:     string;
  shift:     string;
  photo:     null;
  bio:       string;
  username:  string;
  email:     string;
  password:  string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ResponseDetails {
  ctx_title:   string;
  ctx_content: string;
  uri:         string;
  type:        string;
  code:        number;
  status:      string;
  success:     boolean;
}
