// Generated by https://quicktype.io

export interface LoginResponse {
  response: ResponseLoginResponse;
  data:     DataLoginResponse;
}

export interface DataLoginResponse {
  token?:         string;
  refresh_token?: null;
}

export interface ResponseLoginResponse {
  ctx_title:   string;
  ctx_content: string;
  uri:         string;
  type:        string;
  code:        number;
  status:      string;
  success:     boolean;
}
