// Generated by https://quicktype.io

export interface RecoverAccountResponse {
  response: RecoverAccountResponseResponse;
  data:     null;
}

export interface RecoverAccountResponseResponse {
  ctx_title:   string;
  ctx_content: string;
  uri:         string;
  type:        string;
  code:        number;
  status:      string;
  success:     boolean;
}
