// Generated by https://quicktype.io

export interface VerifyTokenResponse {
  response: Response;
  data:     Data;
}

export interface Data {
  token:         string;
  refresh_token: string;
  is_valid:      boolean;
}

export interface Response {
  ctx_title:   string;
  ctx_content: string;
  uri:         string;
  type:        string;
  code:        number;
  status:      string;
  success:     boolean;
}
