// Generated by https://quicktype.io

import { BookEntity } from "./book-entity.interface";

export interface BooksResponse {
  response: ResponseBooksResponse;
  data:     BookEntity[];
}

export interface ResponseBooksResponse {
  ctx_title:   string;
  ctx_content: string;
  uri:         string;
  type:        string;
  code:        number;
  status:      string;
  success:     boolean;
}
