// Generated by https://quicktype.io

import { ApiResponse } from "../../auth/interfaces";
import { BookEntity } from "./book-entity.interface";

export interface BooksResponse {
  response: ApiResponse;
  data:     BookEntity[];
}
