// Generated by https://quicktype.io

export interface BookEntity {
  id:           number;
  cover?:   string;
  title:        string;
  author:       string;
  summary:      string;
  description:  string;
  createdAt:    Date;
  updatedAt:    Date;
}
