// Generated by https://quicktype.io

import { AccountEntity, ApiResponse } from "../../shared/interfaces";
import { BookEntity } from "./book-entity.interface";

export interface ReserveBookResponse {
  response: ApiResponse;
  data:     ReserveBookData[];
}

export interface ReserveBookData {
  id:                number;
  account:           AccountEntity;
  book:              BookEntity;
  account_username:  string;
  account_email:     string;
  account_name:      string;
  account_last_name: string;
  book_title:        string;
  book_author:       string;
  book_count:        number;
  book_price:        number;
  date_from:         Date;
  date_to:           Date;
  active:            boolean;
  status:            string;
  createAt:          Date;
  updateAt:          Date;
}
