// Generated by https://quicktype.io

import { ApiResponse } from "../../shared/interfaces";
import { Announcement } from "./announcement.interface";

export interface AnnouncementResponse {
  response: ApiResponse;
  data:        Announcement[];
}
