// Generated by https://quicktype.io

import { ApiResponse } from "../../shared/interfaces";
import { NotificationAccount } from "./notification-account.interface";

export interface NotificationAccountResponse {
  response: ApiResponse;
  data:     NotificationAccount[];
}
