// Generated by https://quicktype.io

import { ApiResponse } from "../../shared/interfaces";
import { SearchEntity } from "./search-entity.interface";

export interface SearchResponse {
  response: ApiResponse;
  data:     SearchEntity[];
}


